name: esptouch
description: Client-side (mobile) Flutter(Dart) implementation for ESP-Touch protocol
version: 0.0.3
homepage: https://github.com/proarea-co/esptouch/tree/master
authors:
  - Mykhailo Temnokhud <mykhailo.temnokhud@proarea.co>
  - Andrew Kolodiazhnyi <andrew.kolodiazhnyi@proarea.co>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter